### ISSUE TITLE
wiki.en.bin cannot be opened for re-training?

### ISSUE THREAD

**Issue by Sasidhart97** [ericxsun/fastText#11]
Trained the wiki.en.bin
./fasttext supervised -input formed.txt -inputModel wiki.en.bin -output retrained -incr

What(): wiki.wiki.en.bin cannot be opened for re-training
Aborted

A sample of our data looks like this "__label__1 Tom is a good cat"

Please look at my error  and help me?

**Comment by Sasidhart97** [comment]
I rectified it.

**Comment by guoqixin1** [comment]
> I rectified it.

I'm now meet this error. could you tell me how you rectified it? thanks!
