### ISSUE TITLE
Errors during loading Dictionary for word embedding incremental training

### ISSUE THREAD

**Issue by Shiki-H** [ericxsun/fastText#3]
First of all, thank you very much for the great work. Would really appreciate this feature. However, as I played around with it, I could not get started on re-training a word embedding model. Here are the steps to reproduce the error:
```
# run the sample script first to generate a model
$ bash word-vector-example.sh

# after the model is generated from the sample script
# we run
./fasttext skipgram -input data/fil9 -inputModel result/fil9.bin -output retrained -incr
```

The output displayed was:
```
Update args
Load dict from trained model
Load dict from training data
Read 124M words
Number of words:  218316
Number of labels: 0
Merge dict
Read 124M words
Number of words:  0
Number of labels: 0
terminate called after throwing an instance of 'std::invalid_argument'
  what():  Empty vocabulary. Try a smaller -minCount value.
Aborted
```
I have tried to adjust `-minCount` option, but it did not work. 

After looking at the code, I feel that the error has something to do with
```
dict_->addDict(dictInData, false);
```
from line 744 of `fasttext.cc`, but I am not sure about the exact cause of this problem. In fact, I am a bit confused by why we can load dictionary from the raw text we are supposed to train on.

**Comment by airlsyn** [comment]
A bug, fixed by [the last commit](https://github.com/ericxsun/fastText/commit/1e6637513bdca926e83e540b0a5296dd0878adca). As solved, I'll close this issue. Feel free to re-open it.

**Comment by Shiki-H** [comment]
@ericxsun thanks for the help. Everything works fine now.
