### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by jodotlearn** [ericxsun/fastText#6]
Hi, 
I clone this project and occurs error while executing the command "make"

-------------- first error begin --------------

/opt/workspace/fastText/src/args.cc: In member function ‘void fasttext::Args::printTrainingHelp()’:
/opt/workspace/fastText/src/args.cc:259:7: error: expected primary-expression before ‘<<’ token
       << "  -incr               incremental training, default ["
       ^~
CMakeFiles/fasttext-static.dir/build.make:62: recipe for target 'CMakeFiles/fasttext-static.dir/src/args.cc.o' failed
make[2]: *** [CMakeFiles/fasttext-static.dir/src/args.cc.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/fasttext-static.dir/all' failed
make[1]: *** [CMakeFiles/fasttext-static.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

-------------- first error end --------------

The above error occurs at line 258 in args.cc
The semicolon should be removed.

After remove the semicolon, occurs another errors as follow
-------------- second error begin --------------
Scanning dependencies of target fasttext-static
[  2%] Building CXX object CMakeFiles/fasttext-static.dir/src/args.cc.o
[  5%] Building CXX object CMakeFiles/fasttext-static.dir/src/dictionary.cc.o
[  8%] Building CXX object CMakeFiles/fasttext-static.dir/src/fasttext.cc.o
/opt/workspace/fastText/src/fasttext.cc: In member function ‘void fasttext::FastText::predict(std::istream&, int32_t, bool, fasttext::real, std::__cxx11::string)’:
/opt/workspace/fastText/src/fasttext.cc:440:19: error: declaration of ‘std::istream& in’ shadows a parameter
     std::istream& in,
                   ^~
/opt/workspace/fastText/src/fasttext.cc:440:19: error: ‘in’ declared as reference but not initialized
/opt/workspace/fastText/src/fasttext.cc:441:13: error: expected initializer before ‘k’
     int32_t k,
             ^
/opt/workspace/fastText/src/fasttext.cc:468:31: error: qualified-id in declaration before ‘(’ token
 void FastText::printLabelStats(
                               ^
/opt/workspace/fastText/src/fasttext.cc:509:31: error: qualified-id in declaration before ‘(’ token
 void FastText::printLabelStats(std::istream& in, int32_t k, real threshold)
                               ^
/opt/workspace/fastText/src/fasttext.cc:537:33: error: qualified-id in declaration before ‘(’ token
 void FastText::getSentenceVector(std::istream& in, fasttext::Vector& svec) {
                                 ^
/opt/workspace/fastText/src/fasttext.cc:570:28: error: qualified-id in declaration before ‘(’ token
 void FastText::ngramVectors(std::string word) {
                            ^
/opt/workspace/fastText/src/fasttext.cc:588:37: error: qualified-id in declaration before ‘(’ token
 void FastText::precomputeWordVectors(Matrix& wordVectors) {
                                     ^
/opt/workspace/fastText/src/fasttext.cc:601:22: error: qualified-id in declaration before ‘(’ token
 void FastText::findNN(
                      ^
/opt/workspace/fastText/src/fasttext.cc:631:25: error: qualified-id in declaration before ‘(’ token
 void FastText::analogies(int32_t k) {
                         ^
/opt/workspace/fastText/src/fasttext.cc:663:27: error: qualified-id in declaration before ‘(’ token
 void FastText::trainThread(int32_t threadId) {
                           ^
/opt/workspace/fastText/src/fasttext.cc:702:27: error: qualified-id in declaration before ‘(’ token
 void FastText::loadVectors(std::string filename) {
                           ^
/opt/workspace/fastText/src/fasttext.cc:745:21: error: qualified-id in declaration before ‘(’ token
 void FastText::train(const Args args) {
                     ^
/opt/workspace/fastText/src/fasttext.cc:953:28: error: qualified-id in declaration before ‘(’ token
 void FastText::startThreads() {
                            ^
/opt/workspace/fastText/src/fasttext.cc:981:27: error: qualified-id in declaration before ‘(’ token
 int FastText::getDimension() const {
                           ^
/opt/workspace/fastText/src/fasttext.cc:985:23: error: qualified-id in declaration before ‘(’ token
 bool FastText::isQuant() const {
                       ^
/opt/workspace/fastText/src/fasttext.cc: At global scope:
/opt/workspace/fastText/src/fasttext.cc:989:1: error: expected ‘}’ at end of input
 } // namespace fasttext
 ^
CMakeFiles/fasttext-static.dir/build.make:110: recipe for target 'CMakeFiles/fasttext-static.dir/src/fasttext.cc.o' failed
make[2]: *** [CMakeFiles/fasttext-static.dir/src/fasttext.cc.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/fasttext-static.dir/all' failed
make[1]: *** [CMakeFiles/fasttext-static.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

-------------- second error end --------------

How do I build this project?

**Comment by airlsyn** [comment]
It's okay now.
