### ISSUE TITLE
Installation on windows

### ISSUE THREAD

**Issue by nawabhussain** [ericxsun/fastText#9]
Is installation on windows supported? 
I encounter the following errors:

1. Using make:  c ++ -pthread -std = c ++ 0x -O3 -funroll-loops -c src / args.cc process_begin: CreateProcess (NULL, c ++ -pthread -std = c ++ 0x -O3 -funroll-loops -c src / args .cc, ...) failed. make (e = 2): The system can not find the specified file. make: *** [args.o] Error 2

2. Using cmake:  make: *** No targets specified and no "make" control file found. Stop. (on executing make && make install)

**Comment by airlsyn** [comment]
Nope, caused I'm not available to using windows, the installation did not check on such system.
